name: setup
description: Setup the repository
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v5
      with:
        node-version-file: .node-version
        cache: npm
