plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  NewCops: enable

Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 16
Metrics/ClassLength:
  Max: 140

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
