# TODO: Replace with creds api once on rails 8.2.
# <% def env_or_credentials(*keys) = ENV.fetch(keys.join('__').upcase, Rails.application.credentials.dig(*keys)) %>

default: &default
  adapter: trilogy
  encoding: utf8mb4
  collation: utf8mb4_unicode_520_ci
  host: <%= env_or_credentials(:database, :host) %>
  port: <%= env_or_credentials(:database, :port) %>
  username: <%= env_or_credentials(:database, :username) || ENV['USER'] %>
  password: <%= env_or_credentials(:database, :password) %>

production:
  <<: *default
  database: <%= env_or_credentials(:database, :database) %>

development:
  <<: *default
  database: jobapps_development

test:
  <<: *default
  database: jobapps_test
