name: ci
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rails:
    uses: umts/.github/.github/workflows/integrate-rails-app.yml@main
